In [8]:
import pandas as pd

In [9]:
c=pd.read_csv("clusters.csv",index_col=[0])

In [5]:
# c=c.set_index('company')

In [13]:
c.head(3)

,company,balanc,discount,divers,food,free coff,free lunch,gym,health,ice cream,...,sign bonus,stock option,stress,student loan pay,surf,vacat,women,work environ,work home,yoga
0,3M,45.0,10.0,41.0,0.0,-1.0,0.0,3.0,11.0,0.0,...,0.0,3.0,-5.0,0.0,-2.0,-4.0,-4.0,20.0,0.0,1.0
1,AECOM,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.0,0.0,0.0
2,AT&T,2.0,30.0,8.0,-1.0,0.0,0.0,0.0,12.0,0.0,...,0.0,0.0,-35.0,0.0,0.0,16.0,1.0,19.0,1.0,0.0

In [16]:
sample_size = pd.read_csv('li_samplesize.csv', header= None)
sample_size = sample_size.rename(columns={0: "company", 1: "sample_size"})
t = pd.merge(c, sample_size, how = "left", on = 'company')
# t=t.drop(t.columns[0], axis=1) #get rid of unamed
t = t.set_index('company') #leave only numbers
t = t.div(t.sample_size, axis=0)
t = round(t*100,3)
t = t.drop(labels='sample_size', axis=1) #remove column, we no longer need it
n = t.reset_index()  #no index
# d=pd.read_csv('d.csv')
d = n.set_index('company')  #index
d = d.fillna(0)
d = d.astype(float)

In [29]:
t

,balanc,discount,divers,food,free coff,free lunch,gym,health,ice cream,incent,...,sign bonus,stock option,stress,student loan pay,surf,vacat,women,work environ,work home,yoga
company,,,,,,,,,,,,,,,,,,,,,
3M,0.250,0.056,0.228,0.000,-0.006,0.000,0.017,0.061,0.0,-0.017,...,0.0,0.017,-0.028,0.0,-0.011,-0.022,-0.022,0.111,0.000,0.006
AECOM,0.000,0.000,0.000,-0.231,0.000,0.000,0.000,0.000,0.0,0.000,...,0.0,0.000,0.000,0.0,0.000,0.231,0.000,-0.231,0.000,0.000
AT&T,0.011,0.165,0.044,-0.006,0.000,0.000,0.000,0.066,0.0,0.039,...,0.0,0.000,-0.193,0.0,0.000,0.088,0.006,0.105,0.006,0.000
AbbVie,0.317,0.000,-0.128,0.000,0.000,0.000,0.017,0.033,0.0,-0.011,...,0.0,-0.011,-0.100,0.0,-0.006,0.044,-0.006,-0.044,-0.006,0.000
Abbott Laboratories,0.050,0.028,-0.006,0.000,0.011,0.011,0.011,0.231,0.0,0.011,...,0.0,0.017,-0.072,0.0,0.006,0.077,-0.011,0.160,0.006,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wells Fargo,0.200,0.011,0.028,0.006,0.006,0.000,0.006,0.100,0.0,-0.011,...,0.0,-0.006,-0.117,0.0,0.000,0.050,0.000,0.117,0.000,0.000
WestRock,-0.094,0.000,-0.075,0.038,0.000,0.009,0.000,0.056,0.0,0.009,...,0.0,0.000,-0.056,0.0,0.000,0.038,-0.019,0.151,0.000,0.000
Whirlpool,0.457,0.066,0.149,0.006,0.000,0.000,0.000,-0.033,0.0,0.006,...,0.0,0.000,-0.055,0.0,0.000,0.066,-0.072,0.187,0.000,0.000
World Fuel Services,0.036,0.000,0.018,-0.018,0.018,0.000,0.180,-0.054,0.0,-0.054,...,0.0,0.000,-0.036,0.0,0.000,0.000,-0.036,-0.126,0.018,-0.018
google,0.428,-0.006,-0.044,0.250,0.006,0.006,0.011,0.067,0.0,-0.022,...,0.0,0.006,-0.083,0.0,-0.006,-0.011,0.000,0.117,0.000,0.000

In [30]:
t.mean()

balanc              0.168182
discount            0.050431
divers              0.024077
food                0.012028
free coff           0.005448
free lunch          0.006177
gym                 0.023166
health              0.058315
ice cream           0.000066
incent             -0.010519
pay                 0.505122
perk                0.035691
rais               -0.082017
sign bonus         -0.000155
stock option        0.006934
stress             -0.092950
student loan pay    0.000000
surf               -0.001796
vacat               0.038807
women              -0.014613
work environ        0.134105
work home           0.000928
yoga                0.000149
dtype: float64

In [19]:
t.mean().mean()

0.03772063415805909

In [20]:
t.mean().median()

0.006176795580110499

In [25]:
t.mean().quantile(q=[0.5,0.75,0.90])

0.50    0.006177
0.75    0.037249
0.90    0.118947
dtype: float64